In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Hermanus,ZA,-34.42,19.23,57.00,74,0,4.00,clear sky,2020-10-31 19:36:51
1,1,Rikitea,PF,-23.12,-134.97,75.24,69,0,6.87,clear sky,2020-10-31 19:36:51
2,2,Longyearbyen,SJ,78.22,15.64,24.80,62,75,11.41,broken clouds,2020-10-31 19:36:52
3,3,Susanville,US,40.42,-120.65,60.80,19,1,3.36,clear sky,2020-10-31 19:33:59
4,4,Pokaran,IN,26.92,71.92,72.48,20,0,2.91,very heavy rain,2020-10-31 19:36:52

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [6]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
1,1,Rikitea,PF,-23.12,-134.97,75.24,69,0,6.87,clear sky,2020-10-31 19:36:51
7,7,Camalu,MX,30.85,-116.07,82.99,10,44,4.00,scattered clouds,2020-10-31 19:36:52
12,12,Salalah,OM,17.02,54.09,77.00,33,0,3.36,clear sky,2020-10-31 19:32:47
21,21,Alofi,NU,-19.06,-169.92,75.20,94,78,13.87,light rain,2020-10-31 19:36:52
23,23,Bengkulu,ID,-3.80,102.27,75.67,88,100,4.21,overcast clouds,2020-10-31 19:36:53
24,24,Puerto Ayacucho,VE,5.66,-67.62,87.78,66,95,3.47,heavy intensity rain,2020-10-31 19:36:53
26,26,Kavieng,PG,-2.57,150.80,82.99,76,35,10.56,light rain,2020-10-31 19:36:53
28,28,Davila,PH,18.47,120.58,77.00,65,75,9.17,broken clouds,2020-10-31 19:36:53
29,29,Teahupoo,PF,-17.83,-149.27,84.20,62,20,6.93,few clouds,2020-10-31 19:36:53
31,31,Butaritari,KI,3.07,172.79,81.25,75,100,15.48,overcast clouds,2020-10-31 19:36:53

In [7]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.notnull().sum()

City_ID                109
City                   109
Country                109
Lat                    109
Lng                    109
Max Temp               109
Humidity               109
Cloudiness             109
Wind Speed             109
Current Description    109
Date                   109
dtype: int64

In [8]:
preferred_cities_df.count()

City_ID                109
City                   109
Country                109
Lat                    109
Lng                    109
Max Temp               109
Humidity               109
Cloudiness             109
Wind Speed             109
Current Description    109
Date                   109
dtype: int64

In [9]:
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
Date                   0
dtype: int64

In [11]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
1,1,Rikitea,PF,-23.12,-134.97,75.24,69,0,6.87,clear sky,2020-10-31 19:36:51
7,7,Camalu,MX,30.85,-116.07,82.99,10,44,4.00,scattered clouds,2020-10-31 19:36:52
12,12,Salalah,OM,17.02,54.09,77.00,33,0,3.36,clear sky,2020-10-31 19:32:47
21,21,Alofi,NU,-19.06,-169.92,75.20,94,78,13.87,light rain,2020-10-31 19:36:52
23,23,Bengkulu,ID,-3.80,102.27,75.67,88,100,4.21,overcast clouds,2020-10-31 19:36:53
...,...,...,...,...,...,...,...,...,...,...,...
363,363,Itarema,BR,-2.92,-39.92,81.82,73,89,17.34,overcast clouds,2020-10-31 19:37:14
366,366,Abu Zabad,SD,12.35,29.25,83.98,20,5,6.02,clear sky,2020-10-31 19:37:14
375,375,Mulki,IN,13.10,74.80,78.80,88,40,5.01,mist,2020-10-31 19:37:14
377,377,Grand-Santi,GF,4.25,-54.38,89.67,52,53,7.20,broken clouds,2020-10-31 19:37:15
378,378,Kilindoni,TZ,-7.91,39.67,79.23,79,20,12.15,light rain,2020-10-31 19:37:15

In [13]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,75.24,clear sky,-23.12,-134.97,
7,Camalu,MX,82.99,scattered clouds,30.85,-116.07,
12,Salalah,OM,77.00,clear sky,17.02,54.09,
21,Alofi,NU,75.20,light rain,-19.06,-169.92,
23,Bengkulu,ID,75.67,overcast clouds,-3.80,102.27,
24,Puerto Ayacucho,VE,87.78,heavy intensity rain,5.66,-67.62,
26,Kavieng,PG,82.99,light rain,-2.57,150.80,
28,Davila,PH,77.00,broken clouds,18.47,120.58,
29,Teahupoo,PF,84.20,few clouds,-17.83,-149.27,
31,Butaritari,KI,81.25,overcast clouds,3.07,172.79,

In [16]:
len(hotel_df)

109

In [17]:
# 6a. Set parameters to search for hotels with 5000 meters.

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": g_key
    }

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
        
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")

In [18]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head()

        City Country  Max Temp Current Description    Lat     Lng Hotel Name
1    Rikitea      PF     75.24           clear sky -23.12 -134.97    Rikitea
7     Camalu      MX     82.99    scattered clouds  30.85 -116.07     Camalú
12   Salalah      OM     77.00           clear sky  17.02   54.09    Salalah
21     Alofi      NU     75.20          light rain -19.06 -169.92      Alofi
23  Bengkulu      ID     75.67     overcast clouds  -3.80  102.27   Bengkulu

In [19]:
# 8a. Create the output File (CSV)
# Create the output file (CSV).
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [22]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [23]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

In [24]:
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))